# Site settings
title: True Worshippers Evangelistic Centre
email: twectt@gmail.com
description: Roster for singers
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://roster.trueworshippers.org" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
